[build]
  command = "npm run netlify-build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# This redirect ensures that social media crawlers see our custom index.html with metadata
[[redirects]]
  from = "https://kiwi-cryptos.netlify.app/"
  to = "/index.html"
  status = 200
  force = true
  conditions = {Crawler = true}

# Standard redirects for the app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Add headers for images to ensure proper content type
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "image/png"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"
  NETLIFY_NEXT_PLUGIN_SKIP = "true" 